# text_replace { #text_processor.text_replace }

`text_replace`

A module that reads a text file, replaces all instances of a string
with another string, then writes the output to a new file.

## Functions

| Name | Description |
| --- | --- |
| [text_replace](#text_processor.text_replace.text_replace) | Replaces all instances of a string with another string in a text |

### text_replace { #text_processor.text_replace.text_replace }

```python
text_replace.text_replace(input_path, output_path, old, new)
```

Replaces all instances of a string with another string in a text
file, then writes the result into another file. If the old string does
not exist in the file, then the output will be the same unaltered file.

#### Parameters {.doc-section .doc-section-parameters}

| Name        | Type   | Description                                                                                | Default    |
|-------------|--------|--------------------------------------------------------------------------------------------|------------|
| input_path  | str    | An existing file path to the text file to read. The file must be readable.                 | _required_ |
| output_path | str    | The file path to write the replaced text to. The file, should it exist, must be writeable. | _required_ |
| old         | str    | A (non-empty) string to replace.                                                           | _required_ |
| new         | str    | The replacement string.                                                                    | _required_ |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description   |
|--------|--------|---------------|
|        | None   |               |

#### Examples {.doc-section .doc-section-examples}

```python
>>> text_replace("example.txt", "replaced.txt", "color", "colour")
# replaced.txt contains the contents of example.txt, but with all
# instances of 'color' replaced with "colour"
```