# text_lower { #text_processor.text_lower }

`text_lower`



## Functions

| Name | Description |
| --- | --- |
| [text_lower](#text_processor.text_lower.text_lower) | Converts all characters in a text file to lowercase, then writes the result into another file. If empty input file is provided, it will create an empty output file. |

### text_lower { #text_processor.text_lower.text_lower }

```python
text_lower.text_lower(input_path, output_path)
```

Converts all characters in a text file to lowercase, then writes the result into another file. If empty input file is provided, it will create an empty output file.

#### Parameters {.doc-section .doc-section-parameters}

| Name        | Type   | Description                                                                                                                                           | Default    |
|-------------|--------|-------------------------------------------------------------------------------------------------------------------------------------------------------|------------|
| input_path  | str    | Path to the input text file. Must be a string ending with .txt                                                                                        | _required_ |
| output_path | str    | Path to write the processed text file. Must be a string ending with .txt. If input and output paths are the same, the input file will be overwritten. | _required_ |

#### Returns {.doc-section .doc-section-returns}

| Name   | Type   | Description                                                |
|--------|--------|------------------------------------------------------------|
|        | None   | Function writes directly to a UTF-8 file and returns None. |

#### Raises {.doc-section .doc-section-raises}

| Name   | Type              | Description                                                       |
|--------|-------------------|-------------------------------------------------------------------|
|        | TypeError         | If input_path or output_path is not a string.                     |
|        | ValueError        | If input_path or output_path does not have a .txt file extension. |
|        | FileNotFoundError | If the input file does not exist.                                 |
|        | OSError           | If there is an error reading from or writing to the file.         |

#### Examples {.doc-section .doc-section-examples}

```python
>>> text_lower("example.txt", "example_lower.txt")
```